## Google trends interpolation
- In this passage i am going to get the data in csv from google trends page in weekly format
- Create a new list of daily trends through interpolation method
- export the file in order to later use it in the model

In [1]:
# Import libraries
import pandas as pd
import datetime

In [3]:
# read the csv
gtrends = pd.read_csv('googletrends_final.csv', sep=';')
gtrends.head()

         Date  Score
0  2017-08-13     15
1  2017-08-20     14
2  2017-08-27     16
3  2017-09-03     15
4  2017-09-10     13

In [4]:
len(gtrends)

197

In [5]:
# creating a new df where will append the gtrends
new_df = pd.DataFrame()
new_df["Date"] = pd.date_range(start='2017-08-13', end='2021-05-16')
new_df

           Date
0    2017-08-13
1    2017-08-14
2    2017-08-15
3    2017-08-16
4    2017-08-17
...         ...
1368 2021-05-12
1369 2021-05-13
1370 2021-05-14
1371 2021-05-15
1372 2021-05-16

[1373 rows x 1 columns]

In [6]:
list_trends = gtrends['Score'].to_list()

In [7]:
# creating the list to interpolate
list = []
for i in list_trends:
    list.append(i)
    list.append(None)
    list.append(None)
    list.append(None)
    list.append(None)
    list.append(None)
    list.append(None)
list

[15,
 None,
 None,
 None,
 None,
 None,
 None,
 14,
 None,
 None,
 None,
 None,
 None,
 None,
 16,
 None,
 None,
 None,
 None,
 None,
 None,
 15,
 None,
 None,
 None,
 None,
 None,
 None,
 13,
 None,
 None,
 None,
 None,
 None,
 None,
 11,
 None,
 None,
 None,
 None,
 None,
 None,
 9,
 None,
 None,
 None,
 None,
 None,
 None,
 9,
 None,
 None,
 None,
 None,
 None,
 None,
 12,
 None,
 None,
 None,
 None,
 None,
 None,
 14,
 None,
 None,
 None,
 None,
 None,
 None,
 11,
 None,
 None,
 None,
 None,
 None,
 None,
 14,
 None,
 None,
 None,
 None,
 None,
 None,
 15,
 None,
 None,
 None,
 None,
 None,
 None,
 14,
 None,
 None,
 None,
 None,
 None,
 None,
 21,
 None,
 None,
 None,
 None,
 None,
 None,
 31,
 None,
 None,
 None,
 None,
 None,
 None,
 37,
 None,
 None,
 None,
 None,
 None,
 None,
 48,
 None,
 None,
 None,
 None,
 None,
 None,
 44,
 None,
 None,
 None,
 None,
 None,
 None,
 29,
 None,
 None,
 None,
 None,
 None,
 None,
 39,
 None,
 None,
 None,
 None,
 None,
 None,
 49,
 None,
 None,
 None,
 None,
 None,
 None,
 40,
 None,
 None,
 None,
 None,
 None,
 None,
 25,
 None,
 None,
 None,
 None,
 None,
 None,
 25,
 None,
 None,
 None,
 None,
 None,
 None,
 23,
 None,
 None,
 None,
 None,
 None,
 None,
 16,
 None,
 None,
 None,
 None,
 None,
 None,
 15,
 None,
 None,
 None,
 None,
 None,
 None,
 12,
 None,
 None,
 None,
 None,
 None,
 None,
 12,
 None,
 None,
 None,
 None,
 None,
 None,
 12,
 None,
 None,
 None,
 None,
 None,
 None,
 12,
 None,
 None,
 None,
 None,
 None,
 None,
 12,
 None,
 None,
 None,
 None,
 None,
 None,
 10,
 None,
 None,
 None,
 None,
 None,
 None,
 9,
 None,
 None,
 None,
 None,
 None,
 None,
 9,
 None,
 None,
 None,
 None,
 None,
 None,
 11,
 None,
 None,
 None,
 None,
 None,
 None,
 11,
 None,
 None,
 None,
 None,
 None,
 None,
 11,
 None,
 None,
 None,
 None,
 None,
 None,
 8,
 None,
 None,
 None,
 None,
 None,
 None,
 9,
 None,
 None,
 None,
 None,
 None,
 None,
 8,
 None,
 None,
 None,
 None,
 None,
 None,
 7,
 None,
 None,
 None,
 None,
 None,
 None,
 8,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 7,
 None,
 None,
 None,
 None,
 None,
 None,
 8,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 7,
 None,
 None,
 None,
 None,
 None,
 None,
 8,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 9,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 7,
 None,
 None,
 None,
 None,
 None,
 None,
 9,
 None,
 None,
 None,
 None,
 None,
 None,
 7,
 None,
 None,
 None,
 None,
 None,
 None,
 10,
 None,
 None,
 None,
 None,
 None,
 None,
 13,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 9,
 None,
 None,
 None,
 None,
 None,
 None,
 7,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 7,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 8,
 None,
 None,
 None,
 None,
 None,
 None,
 7,
 None,
 None,
 None,
 None,
 None,
 ...]

In [8]:
#create a list witht the same length
list = list[:1373]
len(list)

1373

In [9]:
# new list obtained
new_df['trends'] = list
new_df

           Date  trends
0    2017-08-13    15.0
1    2017-08-14     NaN
2    2017-08-15     NaN
3    2017-08-16     NaN
4    2017-08-17     NaN
...         ...     ...
1368 2021-05-12     NaN
1369 2021-05-13     NaN
1370 2021-05-14     NaN
1371 2021-05-15     NaN
1372 2021-05-16    79.0

[1373 rows x 2 columns]

In [10]:
# linearinterpolation method to infer the missing trends values
new_df["trends"] = new_df["trends"].interpolate(method = "linear")
new_df

           Date     trends
0    2017-08-13  15.000000
1    2017-08-14  14.857143
2    2017-08-15  14.714286
3    2017-08-16  14.571429
4    2017-08-17  14.428571
...         ...        ...
1368 2021-05-12  91.000000
1369 2021-05-13  88.000000
1370 2021-05-14  85.000000
1371 2021-05-15  82.000000
1372 2021-05-16  79.000000

[1373 rows x 2 columns]

In [14]:
# adapt to the lenght of the thereum price hist.
new_df = new_df.iloc[4:1368]

In [15]:
new_df.to_csv('gtrends_interpolated.csv')